### ISSUE TITLE
README.md deprecation notice - document new process

### ISSUE THREAD

**Issue by tysonstewart** [SonarSource/sonarqube-roslyn-sdk#102]
Hello, and thank you for this project! We've been using it successfully for several months in our organization to enforce some tedious-to-remember gotchas in code review. I came back around to the project recently to check out the latest features and I saw the [deprecation notice](https://github.com/SonarSource/sonarqube-roslyn-sdk#deprecation-of-the-roslyn-sdk-by-mmf-1332). At first I was very excited as the current process is quite a few steps: create the analyzer, create and host the Nuget package, use this project to create a jar file, deploy that file to our SonarQube server, test with a pull request. 

I started searching for documentation on how to use the new automatic import but I couldn't find anything that described how to do it. As I understand it, it seems like the expectation is that analyzers are installed as dependencies in .NET solutions so that when they are built, the Sonar Scanner automatically runs the analyzer and imports the results into SonarQube. 

It would be great to document the new workflow as our organization doesn't currently add analyzers as dependencies (we rely on them coming from SonarQube) and are unfamiliar with this process.

Related, but potentially a different issue: I don't think this project should be deprecated because it gives us the ability to distribute and update analyzers centrally, which is how we use analyzers today. Our application code spans hundreds of repos and without this centralized place for our analyzers, we would have to visit and update every repo individually for every analyzer update.

**Comment by duncanp-sonar** [comment]
Hi Tyson,
The documentation on importing issues from external analyzers is [here](https://docs.sonarqube.org/pages/viewpage.action?pageId=11640944).
You're correct - the expectation is that the analyzer packages are added as NuGet packages to the solution, and configured using rulesets in Visual Studio. However, the documentation isn't very clearly worded. I've created [an issue](https://github.com/SonarSource/sonar-scanner-msbuild/issues/662) to track this.

I take the point about manually updating every project, and will feed it back.

**Comment by tysonstewart** [comment]
Thank you!

**Comment by duncanp-sonar** [comment]
I've updated the [documentation](https://docs.sonarqube.org/pages/viewpage.action?pageId=11640944). Let me know if you think it needs further clarification.

**Comment by tysonstewart** [comment]
It makes sense to me. Thanks again for working on this issue @duncanp-sonar!
