### ISSUE TITLE
Unable to create plugin for analyzer created using Rosyln v2.9.0

### ISSUE THREAD

**Issue by feliciateo** [SonarSource/sonarqube-roslyn-sdk#104]
I am using VS2017 version 15.9.2 (Rosyln v2.9.0). I created an analyzer using the Analyzer with Code Fix (.NET standard) project template. I tried to generate SQ plugin using SonarQube.Roslyn.SDK-2.0 but failed. 
I understand that it only support up to Rosyln v2.8.0.0. Will a version that supports Rosyln v2.9.0 and above be made available soon?

**Comment by duncanp-sonar** [comment]
I don't have a timescale for updating the SDK at present. However, here's a workaround you can try in the meantime:

### Workaround
1. Download and unzip the generator
2. Edit the file `RoslynSonarQubePluginGenerator.exe.config` and replace `oldVersion="0.0.0.0-2.8.0.0"` with `oldVersion="0.0.0.0-2.10.0.0"`
i.e. redirect any references to the new version of Roslyn to the version currently used by the generator.

**Comment by sodeshpa** [comment]
Hello,

Can you please take a look at the issue below: WebConfigAnalyzer #112

https://github.com/security-code-scan/security-code-scan/issues/112#event-2236019234

It will be helpful if you can revert quickly

Thanks
Sonali

**Comment by duncanp-sonar** [comment]
@sodeshpa this is issue is closed. If your issue is the same, the workaround given above should help you fix it.

If your issue is not the same, please create a separate issue with more detail about the error message.
Just saying "3. this is failing" is not useful.
