### ISSUE TITLE
[NuGet] Attempting to resolve dependency 'Microsoft.CodeAnalysis.Analyzers (≥ 1.1.0)'. Failed to install package: Unable to resolve dependency 'Microsoft.CodeAnalysis.Analyzers (≥ 1.1.0)'. Check that there are released versions of the package, or specify a pre-release version identifier.

### ISSUE THREAD

**Issue by kumardharm** [SonarSource/sonarqube-roslyn-sdk#105]
I downloaded the Wintellect.Analyzers https://github.com/Wintellect/Wintellect.Analyzers and exported it in visual studio 2017.

Created nupsec file, and the nupkg file.

Now, when I use the rosylngenerator to create the jar file, by passing the path of nupkg in NuGet.config local feed. I am getting the below error.

[NuGet] Attempting to resolve dependency 'Microsoft.CodeAnalysis.Analyzers (≥ 1.1.0)'. Failed to install package: Unable to resolve dependency 'Microsoft.CodeAnalysis.Analyzers (≥ 1.1.0)'. Check that there are released versions of the package, or specify a pre-release version identifier.

Please help me, why I am stuck over here.

Nuget 4+
VS2017

**Comment by duncanp-sonar** [comment]
There is already a public NuGet package for the Wintellect Analyzers (https://www.nuget.org/packages/Wintellect.Analyzers/). Why are you creating your own, rather than just pointing the generator at the publicly available one?

**Comment by kumardharm** [comment]
Can you help me, how do I write custom C# code with this Wintellect Analyzers .

**Comment by duncanp-sonar** [comment]
Check your local NuGet.config also points to the public NuGet.org feed.

**Comment by kumardharm** [comment]
Created one new .net project add in plugin manager Install-Package Wintellect.Analyzers.
Build the proj, created nuspec file and nupkg file. Now when try to use rosylngenerator  it was throwing an error , no analyser found?

Any Idea?

**Comment by duncanp-sonar** [comment]
I don't understand what you are trying to do.
This SDK is intended to wrap existing NuGet analyzer packages into plugins that can be installed into SonarQube. Which NuGet analyzer package are you trying to turn into a plugin?
a) the _Wintellect.Analyzers_ package that is available on NuGet;
b) the _Wintellect.Analyzers_ package, but you want to build it locally;
c) your own analyzer package that includes all of the rules from the _Wintellect_Analyzers_ package, as well as other rules you written yourself; or
d) something else

**Comment by kumardharm** [comment]
Apologies for incomplete info.
Yes, I wants to build custom analyzer package that may includes all of the rules from the Wintellect_Analyzers package, as well as other rules you written yourself and all of them to be packaged into jar which will get used by sonarqube hosted on remote server.

**Comment by duncanp-sonar** [comment]
It would be easier to generate two plugins, one for your own custom rules and one for the _Wintellect.Analyzers_.

Creating a plugin for the published _Wintellect.Analyzers_ is as simple as running ` RoslynSonarQubePluginGenerator.exe /a:Wintellect.Analyzers ` from the command line. You don't need to create any C# project files locally.

Creating a new custom analyzer package for your rules is straightforward using the Roslyn "Analyzer and Code Fix" project template in Visual Studio. This creates a solution that contains one new rule, and that is correctly configured to generate a NuGet package on build. More info and links on creating your own analyzers [here](https://docs.microsoft.com/en-us/visualstudio/extensibility/getting-started-with-roslyn-analyzers?view=vs-2017). Put the new NuGet package in a local NuGet feed and run the generator against it.

If you really want to have a single plugin that contains the Wintellect rules and your own, you have two options:
1) clone the _Wintellect.Analyzers_ repo, Check that you can build it locally. The build will produce a NuGet package. Put this is a local NuGet feed and run the generator against it. There is no need to create any other C# projects. Just write your own rules as part of the Wintellect project, re-build, and re-run the generator.
2) The alternative is more complicated and less well tested. First, create your own custom analyzer package as above, and check that you can run the generator against it correctly. Now, specify the _Wintellect.Analyzers_ as a dependency in your _.nuspec_ (see [here](https://docs.microsoft.com/en-us/nuget/reference/nuspec#dependencies-)). Now build and re-run the generator against _your_ NuGet package, but this time specify the _/recurse_ option on the generator command line e.g. `RoslynSonarQubePluginGenerator.exe /a:MyAnalyzer /recurse`
This tells the generator to look for rules in the package specified on the command line and its dependencies.

**Comment by kumardharm** [comment]
Hi ,
Thanks for your reply.
I am new to this technology and not able to follow the instruction correctly. But I am curious to learn how to write custom sonar rules for C#/.Net projects.
If you can please spare few minutes to guide me on steps,  I will setup a webex call with you. 

Thanking you for your assistance.

**Comment by duncanp-sonar** [comment]
Hi. I'm sorry but I can't help you directly with writing Roslyn analyzers. If you didn't find the link above to the official documentation on creating analyzers helpful, you could try the [series of postings](https://joshvarty.com/learn-roslyn-now/) and videos by Josh Varty. For example, there's a [video](https://www.youtube.com/watch?v=RBTBHRsARCk&list=PLxk7xaZWBdUT23QfaQTCJDG6Q1xx6uHdG&index=9) walkthrough that demonstrates creating a new analyzer in VS.

**Comment by kumardharm** [comment]
Hi @duncanp-sonar ,

**I worked on approach one provided by you.**
clone the Wintellect.Analyzers repo, Check that you can build it locally. The build will produce a NuGet package. Put this is a local NuGet feed and run the generator against it. There is no need to create any other C# projects. Just write your own rules as part of the Wintellect project, re-build, and re-run the generator.

**Approach**
1. VS-2017
2. cloned Wintellect.Analyzers from https://github.com/Wintellect/Wintellect.Analyzers
3. No change in .nuspec file
4. build project and ran nuget pack
5. Nupkg file created successfully.

**Issue:**
When running the RoslynSonarQubePluginGenerator.exe /a:Wintellect.Analyzers cmd  in rosyln dsk 
there is an error.

> [NuGet] Attempting to resolve dependency 'Microsoft.CodeAnalysis.Analyzers (≥ 1.1.0)'. Failed to install package: Unable to resolve dependency 'Microsoft.CodeAnalysis.Analyzers (≥ 1.1.0)'. Check that there are released versions of the package, or specify a pre-release version identifier

Note : Updated the NuGet.config file path in local feed, where my nupkg file got created.

Why I am this issue ?

**Comment by duncanp-sonar** [comment]
Building the _Wintellect.Analyzers.sln_ using MSBuild will automatically generate a _Wintellect.Analyzers.1.0.6.0.nupkg_ file under the _Source\Debug_ folder (or _Source\Release_ if you are building a release build). There is no need to run _nuget pack_ separately.

What does the first part of the output from the tool look like (up to the line where it says _Attempting to locate package with id_ ...)?

**Comment by duncanp-sonar** [comment]
The generator is trying to pull down a missing NuGet package. However, the missing package(s) are not available from any of the package sources listed under the _Enabled package sources_.

Check your local NuGet.config also points to the public NuGet.org feed i.e. that it contains the following entry:
```
<add key="nuget.org" value="https://www.nuget.org/api/v2/" />
```

Note however that the official _Wintellect.Analyzers_ package is also available from this public feed so you need to make sure the generator selects the _Wintellect.Analyzers_ package from your local feed, so make sure your local feed is listed first (this is one of the reasons why it is better to create your own analyzer package rather than adding rules to an existing third-party package).

To be on the safe side, you can change the version of the package by updating the assembly version number in 
_Source\Wintellect.Analyzers\Wintellect.Analyzers\Properties\AssemblyInfo.cs_
e.g. 
```
[assembly: AssemblyVersion("1.0.7.0")]
```

... and specify that new version of the package explicitly on the command line e.g.
```
RoslynSonarQubePluginGenerator.exe /a:wintellect.analyzers:1.0.7
```

**Comment by kumardharm** [comment]
Thank you, I am now able to create the jar file.
Can you, please help me on how to add rules in it. Any doc links, it will be helpful

**Comment by duncanp-sonar** [comment]
Great. I find the following useful (the links are already in the thread above, repeating them here):
* Official MS getting started guide: https://docs.microsoft.com/en-us/visualstudio/extensibility/getting-started-with-roslyn-analyzers?view=vs-2017
* https://joshvarty.com/learn-roslyn-now/

**Comment by kumardharm** [comment]
Added on rule in the same wintellect Analyzer but where to add this rule so it will be available in the plugin

**Comment by duncanp-sonar** [comment]
The generator detects all analyzer rules in the NuGet package. So, if you've added a rule to the MSBuild project, rebuild the project to create a new NuGet package, copy the NuGet package to your local NuGet feed, then the run the generator again. If I remember correctly, the console output from the generator shows how many rules it found so you can quickly check that your new rule is included.

**Comment by kumardharm** [comment]
I removed the wintellect.analyzers from the Analyzers list and added the new path of the new Analyzer dll in my debug folder at that time I am able to see the rules added in my analyzer. 
When I pack the file with nuget pack on the same folder  via cmd it creates a nupkg  which is added in local feed.
Stiill while running Rosylngenerator it was showing 11 Analyzers and 14 rules created

**Comment by kumardharm** [comment]
Thanks for you help, i am able to create custom rules.
