### ISSUE TITLE
C# - cs custom analyzer- RoslynSonarQubePluginGenerator.exe unable to generate Jar

### ISSUE THREAD

**Issue by sodeshpa** [SonarSource/sonarqube-roslyn-sdk#111]
Hello,

This is regarding only CS custom analyzers. CodeAnalysis respective DLLs are updated 3.0.0 as per the latest packs now.

Initially it was throwing version related issues for all these refered dlls so as per this article
https://stackoverflow.com/questions/42536506/could-not-load-file-or-assembly-microsoft-codeanalysis-version-1-3-1-0-cultu
added all 3.0 ones to GAC
Now trying to build JAR and it says No analyzers found in the custom created Analyzer dll

C:\SONAR\SonarQube.Roslyn.SDK-2.0>RoslynSonarQubePluginGenerator.exe /a:PRRST.Analyzer
Roslyn Analyzer Plugin Generator for SonarQube 2.0.0.0
Maximum supported Roslyn version: 2.8.0.0
Minimum supported SonarQube version: 6.7 (highest version tested against: 7.3-alpha1)
[DEBUG] Parsed NuGet reference. Id: PRRST.Analyzer, version:
[DEBUG] Fetching NuGet config files...
[DEBUG] Enabled package sources:
[DEBUG]     C:\SONAR\SonarQube.Roslyn.SDK-2.0, machine-wide: False
[DEBUG]     https://dotnet.myget.org/F/roslyn/api/v3/index.json, machine-wide: False
Attempting to locate package with id 'PRRST.Analyzer'
[WARNING] [NuGet] An error occurred while loading packages from 'https://dotnet.myget.org/F/roslyn/api/v3/index.json': The type initializer for 'NuGet.ProxyCache' threw an exception.
[DEBUG] Number of packages located: 1
[DEBUG] Package versions:
  1.0.0 - latest version
[DEBUG] Using version marked as latest.
Version was not specified. Using version 1.0.0.
[NuGet] 'PRRST.Analyzer 1.0.0' already installed.
[DEBUG] Resolving dependencies for PRRST.Analyzer version 1.0.0...
Looking for analyzers in the package...
[DEBUG] Looking for C# analyzers
[DEBUG] Adding AssemblyResolver to current AppDomain assembly resolution.
Loaded assembly: PRRST.Analyzer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
No analyzers found in assembly PRRST.Analyzer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
[DEBUG] Removed AssemblyResolver from current AppDomain assembly resolution.
[WARNING] No analyzers were found in package: PRRST.Analyzer
[WARNING] Re-run this generator with /recurse if plugins should be generated for the dependencies of this package.

**Comment by dishavirk** [comment]
Any solution for this?

**Comment by duncanp-sonar** [comment]
This should be fixed in v3: https://github.com/SonarSource/sonarqube-roslyn-sdk/releases/tag/3.0
