### ISSUE TITLE
Error while generating the plugin for custom analyzer

### ISSUE THREAD

**Issue by projectrvce** [SonarSource/sonarqube-roslyn-sdk#113]
Roslyn Analyzer Plugin Generator for SonarQube 2.0.0.0
Maximum supported Roslyn version: 2.8.0.0
Minimum supported SonarQube version: 6.7 (highest version tested against: 7.3-alpha1)
[DEBUG] Parsed NuGet reference. Id: SecurityCode, version:
[DEBUG] Fetching NuGet config files...
[DEBUG] Enabled package sources:
[DEBUG]     https://www.nuget.org/api/v2/, machine-wide: False
[DEBUG]     C:\LocalNuGetFeed, machine-wide: False
[DEBUG]     C:\Users\meghanar\Downloads\sonarqube\securitycode\security-code-scan-master, machine-wide: False
Attempting to locate package with id 'SecurityCode'
[DEBUG] Number of packages located: 1
[DEBUG] Package versions:
  3.0.0.0 - latest version

[DEBUG] Using version marked as latest.
Version was not specified. Using version 3.0.0.0.
[NuGet] 'SecurityCode 3.0.0.0' already installed.
[DEBUG] Resolving dependencies for SecurityCode version 3.0.0.0...
Looking for analyzers in the package...
[DEBUG] Looking for C# analyzers
[DEBUG] Adding AssemblyResolver to current AppDomain assembly resolution.
Loaded assembly: SecurityCodeScan, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null
[DEBUG] Attempting to resolve assembly 'System.Composition.AttributedModel, Version=1.0.27.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a', requested by '{unknown}'
[DEBUG] Failed to resolve assembly.
Could not instantiate analyzers from 'SecurityCodeScan, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null'.

Error: Exception has been thrown by the target of an invocation.
Loaded assembly: YamlDotNet, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null
No analyzers found in assembly YamlDotNet, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null
[DEBUG] Removed AssemblyResolver from current AppDomain assembly resolution.
[WARNING] No analyzers were found in package: SecurityCode
[WARNING] Re-run this generator with /recurse if plugins should be generated for the dependencies of this package

I have edited the securitycodescan analyzer and wanted to create plugin out of it.
I get message when i try to do generate plugin. Could you please help me in fixing this issue?

**Comment by duncanp-sonar** [comment]
Have at look at [this](https://github.com/SonarSource/sonarqube-roslyn-sdk/issues/110#issuecomment-481683489) which seems to be a very similar issue.

**Comment by kcthennarasu** [comment]
Could you please explain how to generate sonarqube plugin using nuget

**Comment by projectrvce** [comment]
Is the nuget package a custom analyzer?

**Comment by kcthennarasu** [comment]
Yes

**Comment by kcthennarasu** [comment]
I got error message , no packages with specified id were found:

**Comment by projectrvce** [comment]
add the folder containing your nuget package to the packagesources of visual studio
tools->options->nugetpackagemanager

**Comment by kcthennarasu** [comment]
Again I got same error 
An error occurred while loading package from 'http://www.nuget.org/api/v2/': the remote name could not be resolved: ' www.nuget.org'

**Comment by projectrvce** [comment]
Can you post the screenshot of your package sources list that are present in nuget packagemnager

**Comment by kcthennarasu** [comment]
Microsoft visual studio offline packages
C:\program files(x86)\Microsoft SDKs\NugetPackages\ 
I select this check box only

**Comment by projectrvce** [comment]
create your own package source and add the path to your nuget package in it. A new package source can be added by clicking green + icon

**Comment by kcthennarasu** [comment]
![15580061031781363558224](https://user-images.githubusercontent.com/50697821/57850592-e260c480-77fb-11e9-8ab8-fb9c03c61037.jpg)
After that same error.

**Comment by kcthennarasu** [comment]
![15580099729671936250413](https://user-images.githubusercontent.com/50697821/57854055-e9d89b80-7804-11e9-9c58-cf4829efae62.jpg)

**Comment by kcthennarasu** [comment]
![15580118872591496798156](https://user-images.githubusercontent.com/50697821/57855913-6bcac380-7809-11e9-8658-427e4a023c31.jpg)

**Comment by projectrvce** [comment]
My Package source is your package source?

**Comment by kcthennarasu** [comment]
> My Package source is your package source?

Yes

**Comment by kcthennarasu** [comment]
> > My Package source is your package source?
> 
> Yes 
My package source contains packages namely 
MakeConst 
Mstest.testadapter

**Comment by kcthennarasu** [comment]
> My Package source is your package source?

  RoslynSonarQubePluginGenerator /a: MakeConst 

RoslynSonarQubePluginGenerator /a: Mstest.testadapter

**Comment by projectrvce** [comment]
> ![15580061031781363558224](https://user-images.githubusercontent.com/50697821/57850592-e260c480-77fb-11e9-8ab8-fb9c03c61037.jpg)
> After that same error.
but you didnt add the path of the folder containing your nuget package

**Comment by kcthennarasu** [comment]
> > ![15580061031781363558224](https://user-images.githubusercontent.com/50697821/57850592-e260c480-77fb-11e9-8ab8-fb9c03c61037.jpg)
> > After that same error.
> > but you didnt add the path of the folder containing your nuget package

E:\My package source  
Last one is my added nuget package path
Even I added nuget to 
C:\Program Files(x86)\Microsoft SDKs \NuGetPackages\

**Comment by projectrvce** [comment]
Can you check the id of your nuget package? Id of the nuget is not same as the name of the package. Just verify this

**Comment by kcthennarasu** [comment]
> Can you check the id of your nuget package? Id of the nuget is not same as the name of the package. Just verify this

How can I check id ?

**Comment by projectrvce** [comment]
install nuget package explorer and open you nuget package with it. I dont know if we have still better ways, but I usually do this

**Comment by kcthennarasu** [comment]
> install nuget package explorer and open you nuget package with it. I dont know if we have still better ways, but I usually do this

Thank you for kind replies but Still my problem  is alive. Any another way to solve this problem?

**Comment by kcthennarasu** [comment]
> install nuget package explorer and open you nuget package with it. I dont know if we have still better ways, but I usually do this

I failed to identify nuget ID so I was change my package name , I think Package name and nuget  ID was different now.  But problem not solved .
