### ISSUE TITLE
Unable to use template rules of XML

### ISSUE THREAD

**Issue by kumardharm** [SonarSource/sonarqube-roslyn-sdk#115]
HI Team,

This question is regarding usage  of XML template. 

I am able to create the xml rules from template that rule is not executed.

can you please help me out.

Regards,
Dharmendra

**Comment by duncanp-sonar** [comment]
@kumardharm this repo only relates to rules created using Roslyn analyzers.Please ask on the [community forum](https://community.sonarsource.com/c/help).
