### ISSUE TITLE
Security Hotspot Category

### ISSUE THREAD

**Issue by ShriShalini** [SonarSource/sonarqube-roslyn-sdk#118]
I added SecurityHotspot to be one of the issue types along with Code Smell, Vulnerability, Bug. 
But when I tried to run the RoslynSonarQubePluginGenerator.exe that is generated, it gives me the following error:
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'SonarQube.Plugins.Common, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
   at SonarQube.Plugins.Roslyn.Program.Main(String[] args)

I am able to build the solution without any issues. Does anybody have any suggestions on this?

**Comment by pavel-mikula-sonarsource** [comment]
The only guess would be to check if the listed DLL is present in the directory where the exe is started from. Otherwise, there should not be a problem, as long as you managed to build it.

**Comment by aduoer** [comment]
> 我将 SecurityHotspot 与 Code Smell、Vulnerability、Bug 一起添加为问题类型之一。但是当我尝试运行生成的RoslynSonarQubePluginGenerator.exe时，它给我以下错误：未处理的异常：System.IO.FileNotFoundException：无法加载文件或程序集 'SonarQube.Plugins.Common， Version=2.0.0.0， Culture=neutral， PublicKeyToken=null' 或其依赖项之一。系统找不到指定的文件。在 SonarQube.Plugins.Roslyn.Program.Main（String[] args）
> 
> 我能够毫无问题地构建解决方案。有人对此有什么建议吗？

Do you now know how to define C# rules for security hotspot types?

**Comment by pavel-mikula-sonarsource** [comment]
See Advanced Scenarios in the readme: https://github.com/SonarSource/sonarqube-roslyn-sdk?tab=readme-ov-file#advanced-scenarios.
I haven't try, but using <type>SECURITY_HOTSPOT</type> could do the trick.
