### ISSUE TITLE
Support analyzers created using VS2022

### ISSUE THREAD

**Issue by duncanp-sonar** [SonarSource/sonarqube-roslyn-sdk#123]
### Description

It should be possible to run the exe against analyzers created using the default analyzer template in VS2022.

### Repro
1. Unfold a new analyzer template using the latest updated of VS2022
2. Build the solution
3. Run the SDK exe against the resulting NuGet package

### Expected result
A jar is created successfully

### Actual result
The jar is not created. The error log contains the following output:

```
Loaded assembly: VS2019Analyzer1, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
[DEBUG] Attempting to resolve assembly 'Microsoft.CodeAnalysis, Version=2.10.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35', requested by '{unknown}'
[DEBUG] Failed to resolve assembly.
[DEBUG] Attempting to resolve assembly 'Microsoft.CodeAnalysis.Workspaces, Version=2.10.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35', requested by '{unknown}'
[DEBUG] Failed to resolve assembly.
Could not instantiate analyzers from 'VS2019Analyzer1, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

Error: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
```

### Notes
The current stable version of Roslyn is v3.3.3. However, the analyzer template references Workspace 2.10.

**Comment by themightyzek** [comment]
Is this issue being actively worked on? @duncanp-sonar is there a workaround for this? When Microsoft.CodeAnalysis.Workspaces is added to the directory containing the analyzer, it starts asking for other dependencies(System.Memory, System.Threading.Tasks.Extensions)
