### ISSUE TITLE
How to run RoslynSonarQubePluginGenerator.exe in Azure DevOps

### ISSUE THREAD

**Issue by naveenkumarmca** [SonarSource/sonarqube-roslyn-sdk#127]
Dear Team,

We are facing or not knowing how to run this exe in Azure DevOps environment. Our ultimate goal is to generate jar file from nupkg file. I am able to build nupkg file from Build Solution Task. But stuck on this particular RoslynSonarQubePluginGenerator execution.

Please let me know your inputs on this. TIA.

**Comment by duncanp-sonar** [comment]
There is no specific integration for Azure DevOps pipelines. However, the SDK is just an exe so you can just call it from a PowerShell/script step in your pipeline after you have built your NuGet package.

If you are using self-hosted build agents you could install the exe directly onto your build agents.
If you are using a Microsoft-hosted build agent you would need to automate installing the SDK exe as part of the pipeline. There are couple of ways you could do this e.g.
1) write a PowerShell script to download and unzip the SDK from the releases page of this repo, or
2) you could upload the SDK zip to your Azure Pipelines Library as a [secure file](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/secure-files?view=azure-devops) and use the the `Download Secure File` task to download it to the build agent, and then unzip it using PowerShell/script.
