### ISSUE TITLE
Generated jar files do not unzip correctly on Linux

### ISSUE THREAD

**Issue by duncanp-sonar** [SonarSource/sonarqube-roslyn-sdk#128]
#### Description
If the analyzer being packaged has backslashes as path separators rather than forward slashes then the static resources embedded in the generated jar file will not unzip correctly on Linux machines.

#### Related
[Community thread](https://community.sonarsource.com/t/sonarscanner-dependencies-unpack-incorrectly-linux/12090/2)
PR: #116. Is it possible to use forward-slashes in paths when encoding the zip, rather bulk replacing backslashes when unzipping?

**Comment by tnoiretisa** [comment]
Hi, is there any planning to merge this PR?
It’s really very impactful for us.
Thank you in advance
