### ISSUE TITLE
New changes made in the custom plug in code are not reflecting

### ISSUE THREAD

**Issue by naveenkumarmca** [SonarSource/sonarqube-roslyn-sdk#131]
New changes made in the custom plug in code are not reflecting unless we delete the file/folder in C:\Users\XXXX\AppData\Local\Temp\.sonarqube.sdk\.nuget\

XXXX.rules.template.xml file still contains old code/data and even jar also.

Can you please guide us on this ?

**Comment by duncanp-sonar** [comment]
Are you updating the package version each time you make a change to the code? If not, the SDK will assume it hasn't changed and will used the cached version.

**Comment by naveenkumarmca** [comment]
Hi @duncanp-sonar , Any alternate way or configuration to avoid it from using cached version ?

**Comment by duncanp-sonar** [comment]
@naveenkumarmca, write a script to delete the cached version before running the SDK tool.

**Comment by naveenkumarmca** [comment]
Ok Fine
