### ISSUE TITLE
Unable to generate for microsoft.netcore.analyzers

### ISSUE THREAD

**Issue by PeteBoyRocket** [SonarSource/sonarqube-roslyn-sdk#133]
When I run this command:
`.\RoslynSonarQubePluginGenerator.exe /a:microsoft.netcore.analyzers /recurse`

I get this log:

[output.log](https://github.com/SonarSource/sonarqube-roslyn-sdk/files/3594544/output.log)

`Error: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
Loaded assembly: Microsoft.NetCore.Analyzers.resources, Version=2.9.4.0, Culture=cs, PublicKeyToken=31bf3856ad364e35
No analyzers found in assembly Microsoft.NetCore.Analyzers.resources, Version=2.9.4.0, Culture=cs, PublicKeyToken=31bf3856ad364e35
Loaded assembly: Microsoft.NetCore.Analyzers.resources, Version=2.9.4.0, Culture=de, PublicKeyToken=31bf3856ad364e35
No analyzers found in assembly Microsoft.NetCore.Analyzers.resources, Version=2.9.4.0, Culture=de, PublicKeyToken=31bf3856ad364e35
Loaded assembly: Microsoft.NetCore.Analyzers.resources, Version=2.9.4.0, Culture=es, PublicKeyToken=31bf3856ad364e35
No analyzers found in assembly Microsoft.NetCore.Analyzers.resources, Version=2.9.4.0, Culture=es, PublicKeyToken=31bf3856ad364e35
Loaded assembly: Microsoft.NetCore.Analyzers.resources, Version=2.9.4.0, Culture=fr, PublicKeyToken=31bf3856ad364e35
No analyzers found in assembly Microsoft.NetCore.Analyzers.resources, Version=2.9.4.0, Culture=fr, PublicKeyToken=31bf3856ad364e35
Loaded assembly: Microsoft.NetCore.Analyzers.resources, Version=2.9.4.0, Culture=it, PublicKeyToken=31bf3856ad364e35
No analyzers found in assembly Microsoft.NetCore.Analyzers.resources, Version=2.9.4.0, Culture=it, PublicKeyToken=31bf3856ad364e35
Loaded assembly: Microsoft.NetCore.Analyzers.resources, Version=2.9.4.0, Culture=ja, PublicKeyToken=31bf3856ad364e35
No analyzers found in assembly Microsoft.NetCore.Analyzers.resources, Version=2.9.4.0, Culture=ja, PublicKeyToken=31bf3856ad364e35
Loaded assembly: Microsoft.NetCore.Analyzers.resources, Version=2.9.4.0, Culture=ko, PublicKeyToken=31bf3856ad364e35
No analyzers found in assembly Microsoft.NetCore.Analyzers.resources, Version=2.9.4.0, Culture=ko, PublicKeyToken=31bf3856ad364e35
Loaded assembly: Microsoft.NetCore.Analyzers.resources, Version=2.9.4.0, Culture=pl, PublicKeyToken=31bf3856ad364e35
No analyzers found in assembly Microsoft.NetCore.Analyzers.resources, Version=2.9.4.0, Culture=pl, PublicKeyToken=31bf3856ad364e35
Loaded assembly: Microsoft.NetCore.Analyzers.resources, Version=2.9.4.0, Culture=pt-BR, PublicKeyToken=31bf3856ad364e35
No analyzers found in assembly Microsoft.NetCore.Analyzers.resources, Version=2.9.4.0, Culture=pt-BR, PublicKeyToken=31bf3856ad364e35
Loaded assembly: Microsoft.NetCore.Analyzers.resources, Version=2.9.4.0, Culture=ru, PublicKeyToken=31bf3856ad364e35
No analyzers found in assembly Microsoft.NetCore.Analyzers.resources, Version=2.9.4.0, Culture=ru, PublicKeyToken=31bf3856ad364e35
Loaded assembly: Microsoft.NetCore.Analyzers.resources, Version=2.9.4.0, Culture=tr, PublicKeyToken=31bf3856ad364e35
No analyzers found in assembly Microsoft.NetCore.Analyzers.resources, Version=2.9.4.0, Culture=tr, PublicKeyToken=31bf3856ad364e35
Loaded assembly: Microsoft.NetCore.Analyzers.resources, Version=2.9.4.0, Culture=zh-Hans, PublicKeyToken=31bf3856ad364e35
No analyzers found in assembly Microsoft.NetCore.Analyzers.resources, Version=2.9.4.0, Culture=zh-Hans, PublicKeyToken=31bf3856ad364e35
Loaded assembly: Microsoft.NetCore.Analyzers.resources, Version=2.9.4.0, Culture=zh-Hant, PublicKeyToken=31bf3856ad364e35
No analyzers found in assembly Microsoft.NetCore.Analyzers.resources, Version=2.9.4.0, Culture=zh-Hant, PublicKeyToken=31bf3856ad364e35
[DEBUG] Removed AssemblyResolver from current AppDomain assembly resolution.
[WARNING] No analyzers were found in package: Microsoft.NetCore.Analyzers`

**Comment by tnoiretisa** [comment]
Hi, You can try to get my pending pull request : https://github.com/SonarSource/sonarqube-roslyn-sdk/pull/126

**Comment by PeteBoyRocket** [comment]
@tnoiretisa Finally got round to trying this, your changes worked!
