### ISSUE TITLE
Visual Studio Version for Sonar Custom Plugin

### ISSUE THREAD

**Issue by AnanthaSubramanian** [SonarSource/sonarqube-roslyn-sdk#134]
Hi Team,

I understand I need to use Visual Studio Version which has roslyn version less than 2.8.2.
Ref: https://docs.microsoft.com/en-us/visualstudio/extensibility/roslyn-version-support?view=vs-2019
So Ideally I need to use Visual Studio version 15.7 or lesser from Visual Studio 2017.
Ref: https://docs.microsoft.com/en-us/visualstudio/productinfo/installing-an-earlier-release-of-vs2017#top

But if I download any of the version listed in above link- I am getting error as 
"Severity	Code	Description	Project	File	Line	Suppression State
Error		The current .NET SDK does not support targeting .NET Core 2.0.  Either target .NET Core 1.1 or lower, or use a version of the .NET SDK that supports .NET Core 2.0.	FISCSharpCAAnalyzer.Test	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.TargetFrameworkInference.targets	112"

This is specifically for test project. In such case I am not sure which version are you suggesting to use and how to install that specific version?
Can some one help.

P.S. Visual Studio 2017 15.9 Version there are no issues as mentioned above however, as per Sonar Documentation this version is not compatible.

Regards,
Anantha
9740955371

**Comment by duncanp-sonar** [comment]
@AnanthaSubramanian,
> I understand I need to use Visual Studio Version which has roslyn version less than 2.8.2.

No, that isn't correct. Your analyzer project needs to reference a version of the Roslyn NuGet packages that is equal to 2.8.2 or lower. You can use a newer version of VS e.g. VS2019 would work fine.

**Comment by AnanthaSubramanian** [comment]
Thanks for the details.
