### ISSUE TITLE
Issue while creating plugin

### ISSUE THREAD

**Issue by AnanthaSubramanian** [SonarSource/sonarqube-roslyn-sdk#138]
### Description

Please provide a succinct description of your issue.
I was able to generate plugin with VS2017 v15.7.6 and V15.9.8 till today morning.
Suddenly without me changing anything I am getting error while trying to create plugin file(jar file)-

" Attempting to resolve assembly 'Microsoft.CodeAnalysis, Version=2.9.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35', requested by '{unknown}'

The above line is repeated 4 times more, then-

Could not instantiate analyzers from 'FISCSharpCAAnalyzer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

Error: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information."
 
Note: please ask support questions in the [community forum](https://community.sonarsource.com/c/help/8)

### Repro steps

Please provide the steps required to reproduce the problem

1. Step A
Crate a analyzer using VS2017 V 15.7.6 or 15.9.8
2. Step B
Deploy the plugin in nuget
3.Step C
Create a plugin.
4. Step D
It was all working fine till I created a new anlyzer in VS 2017 V 15.9.8 with project name as "sonar-csharp-perf-plugin". After this suddenly I started seeing this issue as I edited CS Proj file to edit analyzer id and also nuspec file without changing the whole project name at first.
Then, I started receiving this error as stated above.
I created a new project from scratch again in VS2017 15.9.8 and just copied the analyzer code.
This time as well I received the same errors as stated above.

This issue only appear when I am trying to create a plugin- jar file .
Build was happening perfectly fine.

If possible then please create a git repository with a repro sample or attach a zip to the issue.

### Expected behavior
I should get a jar file i.e. a plugin.

Please provide a description of the behavior you expect.

### Actual behavior
I am receiving error as mentioned above.

Please provide a description of the actual behavior you observe.

### Known workarounds

Please provide a description of any known workarounds.

### Related information

* Roslyn version (< 2.8.2 (Whatever comes as default when trying to create a new project using VS2017 Enterprise edition v15.9.8 / v 15.7.6 ))
* Visual Studio Version (e.g. VS 2017 Enterprise v15.9.8 / v 15.7.6)
* Languages targeted by the analyzer (C#)

**Comment by AnanthaSubramanian** [comment]
Exact Error Message as below-

C:\Project\Sonar\Nuget V5.2\NugetRepo>"C:\Project\Sonar\Plugin\SonarQube Roslyn SDK\SonarQube.Roslyn.SDK-2.0\RoslynSonarQubePluginGenerator.exe" /a:FISCSharpCAAnalyzer:1.0.0
Roslyn Analyzer Plugin Generator for SonarQube 2.0.0.0
Maximum supported Roslyn version: 2.8.0.0
Minimum supported SonarQube version: 6.7 (highest version tested against: 7.3-alpha1)
[DEBUG] Parsed NuGet reference. Id: FISCSharpCAAnalyzer, version: 1.0.0
[DEBUG] Fetching NuGet config files...
[DEBUG] Enabled package sources:
[DEBUG]     https://www.nuget.org/api/v2/, machine-wide: False
[DEBUG]     C:\LocalNuGetFeed, machine-wide: False
[DEBUG]     https://dotnet.myget.org/F/roslyn/api/v3/index.json, machine-wide: False
[DEBUG]     C:\Project\Sonar\Nuget V5.2\NugetRepo, machine-wide: False
[DEBUG]     C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\, machine-wide: True
Attempting to locate package with id 'FISCSharpCAAnalyzer'
[WARNING] [NuGet] An error occurred while loading packages from 'https://dotnet.myget.org/F/roslyn/api/v3/index.json': The remote server returned an error: (404) Not Found.
[DEBUG] Number of packages located: 1
[DEBUG] Package versions:
  1.0.0 - latest version

[NuGet] 'FISCSharpCAAnalyzer 1.0.0' already installed.
[DEBUG] Resolving dependencies for FISCSharpCAAnalyzer version 1.0.0...
Looking for analyzers in the package...
[DEBUG] Looking for C# analyzers
[DEBUG] Adding AssemblyResolver to current AppDomain assembly resolution.
Loaded assembly: FISCSharpCAAnalyzer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
[DEBUG] Attempting to resolve assembly 'Microsoft.CodeAnalysis, Version=2.9.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35', requested by '{unknown}'
[DEBUG] Failed to resolve assembly.
[DEBUG] Attempting to resolve assembly 'Microsoft.CodeAnalysis, Version=2.9.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35', requested by '{unknown}'
[DEBUG] Failed to resolve assembly.
[DEBUG] Attempting to resolve assembly 'Microsoft.CodeAnalysis, Version=2.9.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35', requested by '{unknown}'
[DEBUG] Failed to resolve assembly.
[DEBUG] Attempting to resolve assembly 'Microsoft.CodeAnalysis, Version=2.9.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35', requested by '{unknown}'
[DEBUG] Failed to resolve assembly.
[DEBUG] Attempting to resolve assembly 'Microsoft.CodeAnalysis, Version=2.9.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35', requested by '{unknown}'
[DEBUG] Failed to resolve assembly.
Could not instantiate analyzers from 'FISCSharpCAAnalyzer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

Error: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
[DEBUG] Removed AssemblyResolver from current AppDomain assembly resolution.
[WARNING] No analyzers were found in package: FISCSharpCAAnalyzer
[WARNING] Re-run this generator with /recurse if plugins should be generated for the dependencies of this package.

**Comment by duncanp-sonar** [comment]
Looking at the logs you've posted:

> C:\Project\Sonar\Nuget V5.2\NugetRepo>"C:\Project\Sonar\Plugin\SonarQube Roslyn SDK\SonarQube.Roslyn.SDK-2.0\RoslynSonarQubePluginGenerator.exe" /a:FISCSharpCAAnalyzer:1.0.0
Roslyn Analyzer Plugin Generator for SonarQube 2.0.0.0
**Maximum supported Roslyn version: 2.8.0.0**
Minimum supported SonarQube version: 6.7 (highest version tested against: 7.3-alpha1)
...
> [DEBUG] **Attempting to resolve assembly 'Microsoft.CodeAnalysis, Version=2.9.0.0**, Culture=neutral, PublicKeyToken=31bf3856ad364e35', requested by '{unknown}'
[DEBUG] Failed to resolve assembly.

The analyzer NuGet is using a newer version of Roslyn that isn't supported by v2 of the SDK, so that is the first thing to check in your analyzer project.


If you are developing the analyzer on your local machine then there is another thing you need to look out for. The SDK exe caches the NuGet packages it fetches so it doesn't fetch them multiple times. Looking at the log again, we see:
> [DEBUG] Fetching NuGet config files...
...
> [NuGet] 'FISCSharpCAAnalyzer 1.0.0' already installed.

The SDK thinks it has already downloaded the specified version of the package so it doesn't try to download it again.

This means that if you are building the analyzer package locally, adding it to a local feed,  then running the SDK against it, you will have to one of the following before running the SDK. Either
A) increment the package version number each time so the SDK sees it as a new package.
or
B) delete your package from the local cache which is at `%temp%\.sonarqube.sdk\.nuget`

**Comment by AnanthaSubramanian** [comment]
Thanks for the help and important information - "%temp%\.sonarqube.sdk\.nuget"
Thanks again for very prompt help. It worked for me. Plugin got generated.
