### ISSUE TITLE
The 2.0 generator does not work for microsoft.codeanalysis.fxcopanalyzers

### ISSUE THREAD

**Issue by PeteBoyRocket** [SonarSource/sonarqube-roslyn-sdk#145]
### Description

The generator (v2.0) does not work for microsoft.codeanalysis.fxcopanalyzers

`Could not instantiate analyzers from 'Microsoft.NetFramework.CSharp.Analyzers, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
`

### Repro steps

1. Run `RoslynSonarQubePluginGenerator.exe /a:microsoft.codeanalysis.fxcopanalyzers:3.0.0 /recurse /acceptLicenses`

2. View the output - it has errors, and only the `microsoftcodeanalysisversioncheckanalyzer-plugin-3.0.0.jar` is produced.

### Expected behavior

jar for all Microsoft analysers in microsoft.codeanalysis.fxcopanalyzers are produced.

### Actual behavior

only the `microsoftcodeanalysisversioncheckanalyzer-plugin-3.0.0.jar` is produced.

### Known workarounds

none

### Related information

* Roslyn version = VS 2019
* Visual Studio Version = Professional 2019
* Languages targeted by the analyzer = C#, VB.Net

[output.log](https://github.com/SonarSource/sonarqube-roslyn-sdk/files/4857427/output.log)

**Comment by BrightLight** [comment]
We had the same problem. A colleague of mine made some [improvements in his fork](https://github.com/steffen-wilke/sonarqube-roslyn-sdk/commit/cd980ea9eb2accabcde3562eee9354d66f0d77bf). You can give our pre-release a try: [Custom build to work with Microsoft.CodeAnalysis 3.6.0](https://github.com/steffen-wilke/sonarqube-roslyn-sdk/releases/tag/v3.0.0-soloplan). With this we were able to create a SonarQube plugin for the FxCop analyzers. Hope it helps.

**Comment by PeteBoyRocket** [comment]
@BrightLight finally got round to trying this, it worked!
I did have to copy the old nuget.config from the original Sonar 2.0 release https://github.com/SonarSource-VisualStudio/sonarqube-roslyn-sdk/releases/download/2.0/SonarQube.Roslyn.SDK-2.0.zip, otherwise it didn't use the correct nuget feed.

**Comment by duncanp-sonar** [comment]
FYI this should be fixed in v3: https://github.com/SonarSource/sonarqube-roslyn-sdk/releases/tag/3.0
