### ISSUE TITLE
Still alive?

### ISSUE THREAD

**Issue by twenzel** [SonarSource/sonarqube-roslyn-sdk#146]
Is this project still maintained?
Is there are roadmap to support newer Roslyn analyzer than 2.9.2 (e.g. 3.0)?

**Comment by PeteBoyRocket** [comment]
Someone asked the same question on the community forum too. I've added my two cents there too:

https://community.sonarsource.com/t/sonarqube-roslyn-sdk-deprecation/21308

**Comment by pavel-mikula-sonarsource** [comment]
We'll bump to the latest Roslyn this week and update the readme to clarify how anyone can do it by themselves. It should take just bumping the latest Roslyn version here and rebuilding the project
https://github.com/SonarSource/sonarqube-roslyn-sdk/blob/master/Directory.Build.props#L9
