### ISSUE TITLE
Nuget Cache Files

### ISSUE THREAD

**Issue by 123caner123** [SonarSource/sonarqube-roslyn-sdk#149]
Hi,

When I create new jar,it create old jar.I reset the following files.I clear files.
D:\Users\VB36137\AppData\Local\Temp\.sonarqube.sdk\.nuget\codecracker.CSharp.1.0.2\analyzers\dotnet\cs 
D:\Users\VB36137\AppData\Local\Temp\NuGetScratch

Thank You,
Beste Regards

**Comment by pavel-mikula-sonarsource** [comment]
Hi @123caner123,

I don't understand what the problem is. Can you please provide more details?
