### ISSUE TITLE
No packages with the specified id were found

### ISSUE THREAD

**Issue by vb123er951** [SonarSource/sonarqube-roslyn-sdk#150]
Hi, 
I am trying to use the sonarqube.roslyn.sdk to build a custom rule for C#, I already build my .nupkg file from visual studio 2015. While using this sdk it says `No packages with the specified id were found`, but when I using other .nupkg file it can find the file correctly, can you give some suggestions?

the console output is like:
> [DEBUG] Number of packages located: 0
> No packages with the specified id were found: ABCAnalyzer

I put the .nupkg in the same directory with `RoslynSonarQubePluginGenerator.exe`, and my command is
`RoslynSonarQubePluginGenerator.exe /a:ABCAnalyzer`

**Comment by duncanp-sonar** [comment]
The repo Readme has a section on NuGet feeds:
https://github.com/SonarSource/sonarqube-roslyn-sdk#configuring-nuget-feeds

**Comment by pavel-mikula-sonarsource** [comment]
As long as you can reference the package in a .NET project, it raises issues to make sure it works, the package targets supported Roslyn version and you placed it in one of the supported nuget sources, it should work. Othwerwise, we'd need more information about the package.
