### ISSUE TITLE
Error During Jar File Generation 

### ISSUE THREAD

**Issue by ademett2000** [SonarSource/sonarqube-roslyn-sdk#170]
I created a new Project on Visual Studio 2019 choosing the template “Analyzer with Code Fix (.NET Standard). 

![image](https://user-images.githubusercontent.com/94614230/142409538-f076850b-ee45-4619-9d51-2418ca07d7a4.png)

The template automatically creates the following projects:

![image](https://user-images.githubusercontent.com/94614230/142409603-e252cc72-1b6d-40fe-a19f-1e093afec359.png)

The analyzer this template contains checks whether the all the type names contain uppercase letters and complains if not.

I want to create a Jar file for this Project to be able to upload this rule to SonarQube using the following approach:
 
1)	I downloaded SonarQube.Roslyn.SDK-2.0 
2)	Created a NuGet package using a batch file containing the code below: 
cd..
nuget add C:\Users\User1\Desktop\Project\Analyzer\Analyzer.Package\bin\Debug\IntertechSonarAnalyzer.1.0.0.nupkg -source C:\Users\User1\Desktop\Project\Analyzer\Analyzer.Package\bin\Debug\NugetFeeds
Pause

As a consequence, a NugetFeeds folder is created containing the NuGet package as below:

![image](https://user-images.githubusercontent.com/94614230/142409806-832777af-1b5a-427a-afc4-f5d58b1d1f6b.png)

3)	I then edit the Nuget.config file in SonarQube.Roslyn.SDK-2.0 by changing the key to localFeed and the value to "C:\Users\User1\Desktop\Project\Analyzer\Analyzer.Package\bin\Debug\NugetFeeds\analyzer\1.0.0" as below:

![image](https://user-images.githubusercontent.com/94614230/142409852-2ae0da19-a413-404c-8ba6-b079c79adf9b.png)

4)	Finally, I run the RoslynSonarQubePluginGenerator using the command RoslynSonarQubePluginGenerator.exe /a:Analyzer but I get the following warning and the Jar file can’t be created:
 
![image](https://user-images.githubusercontent.com/94614230/142409887-befdd0c6-3aa8-480f-81f6-aed1c68ded76.png)

![image](https://user-images.githubusercontent.com/94614230/142409916-70332e03-9b91-4745-834f-fb55c3e07adf.png)

I would appreciate any help or comments!

**Comment by duncanp-sonar** [comment]
@ademett2000 your analyzer is using a version of Roslyn that is not supported by v2.0 of the SDK:

![image](https://user-images.githubusercontent.com/10757559/142414638-8c61eee9-b1d6-4f9d-bc36-08e7bad0027c.png)

![image](https://user-images.githubusercontent.com/10757559/142414628-67b6d173-07f8-4b33-bb4c-e69d3eb71929.png)

Try the [v3.0-RC1](https://github.com/SonarSource/sonarqube-roslyn-sdk/releases/tag/3.0-RC1), which supports Roslyn v4.
