### ISSUE TITLE
How to change key value in configuration.xml

### ISSUE THREAD

**Issue by ketanmehra30** [SonarSource/sonarqube-roslyn-sdk#183]
Is there any way to change the key inside the configuration.xml. As of now key is "Roslyn + PackageID+ cs. I want to remove  Roslyn and cs hard coded as a value and only need my packageid. Is this possible?

**Comment by duncanp-sonar** [comment]
No, it isn't. The repo key needs to be in this form for the plugin to work correctly with the SonarScanner for .NET. If the key is in a different form, the scanner won't download the analyzer during the `begin` step.

**Comment by ketanmehra30** [comment]
okay, Thanks for reply
