### ISSUE TITLE
Unable pass nuget package file path via cli 

### ISSUE THREAD

**Issue by ketanmehra30** [SonarSource/sonarqube-roslyn-sdk#185]
I am running the whole process of creating new rules and creating nuget package and then feeding it to exe via a powershell script but I don’t want to hard code nuget package path in nuget.config file instead I want to do it via cli. In  repo doc it is mentioned as “/customnugetrepo:file:///PathToRepo” but I am getting error as unrecognized command. Can anyone please give an example how to pass the path.

**Comment by duncanp-sonar** [comment]
Closing as a duplicate of [this forum question](https://community.sonarsource.com/t/how-to-pass-nuget-package-file-path-via-cli-when-using-sonarqube-roslyn-sdk/73913).

The forum is the correct place to ask support questions.
