### ISSUE TITLE
Not Finding Rules in Quality Profiles

### ISSUE THREAD

**Issue by deepanshukhanna** [SonarSource/sonarqube-roslyn-sdk#199]
I have generated the jar file using the generator and then dropped that jar in extensions and then rerun the server, but not able to see any changes under the Quality Profiles. Is there anything i am missing here?

**Comment by matode** [comment]
I have the same observation. 

For the first time after update to SonarQube version higher than 10.0 we tried to upload a new plugin version to the server. New rules are not available and can't be added to the quality profiles.

**Comment by sebastien-marichal** [comment]
Hello @deepanshukhanna,

Does your `rules.xml` contain your rules?

When generating the jar file, if you see the following message:
```
[WARNING] No analyzers were found in package: <your-package>
```
It is most likely the SDK was not able to find your rules.

Could you provide the logs when running the SDK?

Thank you,
---

Hello @matode,

Can you open a dedicated ticket for this?
So we can properly track the different issues.

Please provide the details on how you proceed to generate the jar and the logs.

Thank you,
