### ISSUE TITLE
SonarQube-Roslyn SDK not working for analyzer NuGet packet created using Roslyn v2.6.0

### ISSUE THREAD

**Issue by msbasanth** [SonarSource/sonarqube-roslyn-sdk#69]
Hi,

I tried using latest release for creating a Sonar plugin but failed with error:
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
Could not instantiate analyzers from 'AnalyzerPackageName, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null'.
[DEBUG] Attempting to resolve assembly 'Microsoft.CodeAnalysis, Version=2.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35', requested by '{unknown}'
[DEBUG] Failed to resolve assembly.
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

Even work around given at https://jira.sonarsource.com/browse/SFSRAP-45 also didn't work.

Regards
Basanth

**Comment by msbasanth** [comment]
Hi,

How it fixed:
1. Cloned https://github.com/SonarSource/sonarqube-roslyn-sdk.git
2. Changed below 3 projects targetting to 4.7.1 
                SonarQube.Plugins.Common
                SonarQube.Plugins.PluginGenerator
                SonarQube.Plugins.Roslyn.PluginGenerator
3. Updated the Micrososoft.CodeAnalysis NuGet references to v2.6.0 (the Roslyn version your analyzer package uses) in SonarQube.Plugins.Roslyn.PluginGenerator.csproj.
4. Build SonarQube.Plugins.Roslyn.PluginGenerator.csproj
I have not updated RoslynSonarQubePluginGenerator.exe.config as mentioned in the workaround.
5. ran command:
RoslynSonarQubePluginGenerator.exe /a:<NuGetPackageName>

This generated a SonarQube plugin for your custom analyzer package. Which we can follow standard way of adding plugin to SonarQube.

Thanks
Basanth

**Comment by vickyrocky** [comment]
Hi @msbasanth ,

Can you please guide me for writing custom rule for sonar csharp plugin as i am not able to understand how to use this sonarqube-roslyn-sdk to create a plugin and also there are no proper documentation regarding the same. Thanks in advance!
I need below information:

> After cloning this what are the things to get started i.e from start to end  like dependencies or some command needs to be run

> where to add my rule file and testcases file

> How to run the unit tests 

> How to package this plugin

I know i'm asking a lot but if you can help that would be great.

Thanks

**Comment by duncanp-sonar** [comment]
@vickyrocky the purpose of the SDK is not to help you to write new custom C# rules. The purpose of the SDK is to allow you integrate analysis rules written using the Roslyn framework. The [blog post](https://blogs.msdn.microsoft.com/devops/2016/02/18/sonarqube-scanner-for-msbuild-v2-0-released-support-for-third-party-roslyn-analyzers/) referred to in the readme explains the big picture, which at a very high level is:
1) write your new rules using Roslyn (or choosing the third-party Roslyn analyzer that you want to wrap), and
2) run this SDK against the analyzer package to produce a SonarQube plugin.

There is a lot of documentation on the web about how to write analysis rules using Roslyn e.g. [Getting Started with Roslyn analyzers](https://docs.microsoft.com/en-us/visualstudio/extensibility/getting-started-with-roslyn-analyzers).

Feel free to open a PR with proposed improvements to the documentation.
